"""fix models

Revision ID: 1a9a38bb71ff
Revises: b5d276070340
Create Date: 2025-06-05 21:37:52.753762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9a38bb71ff'
down_revision: Union[str, None] = 'b5d276070340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('operation_log_client_id_fkey'), 'operation_log', type_='foreignkey')
    op.create_foreign_key(None, 'operation_log', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation_log', type_='foreignkey')
    op.create_foreign_key(op.f('operation_log_client_id_fkey'), 'operation_log', 'account', ['client_id'], ['id'])
    # ### end Alembic commands ###
